Update ci_build.yml

diff --git a/.github/workflows/ci_build.yml b/.github/workflows/ci_build.yml
--- a/.github/workflows/ci_build.yml
+++ b/.github/workflows/ci_build.yml
@@ -9,8 +9,10 @@ jobs:
     runs-on: windows-2022
 
     env:
-      WDS_PATH: "${{ github.workspace }}\\windows-driver-samples"
-      CODEQL_ZIP: "codeql-win64.zip"
+      WDS_PATH: ".\windows-driver-samples"
+      CODEQL_BIN: ".\codeql\codeql.exe"
+      X64_DB_PATH: ".\wds-release-x64"
+      ARM64_DB_PATH: ".\wds-release-x64"
       DEST: "${{ github.workspace }}\\extracted_drivers"
 
     steps:
@@ -38,13 +40,31 @@ jobs:
           Remove-Item $CodeqlZip
 
           Write-Host "[+] Verifying CodeQL installation..."
-          ./codeql/codeql.exe --version
+          & $env:CODEQL_BIN --version
 
       - name: Initialize CodeQL Packs
         shell: pwsh
         run: |
-          ./codeql/codeql.exe pack download microsoft/windows-drivers@1.0.13
-          ./codeql/codeql.exe pack download codeql/cpp-queries@0.9.0
+          Write-Host "[+] Download Pack microsoft/windows-drivers@1.0.13..."
+          & $env:CODEQL_BIN pack download microsoft/windows-drivers@1.0.13
+
+          Write-Host "[+] Download Pack codeql/cpp-queries@0.9.0..."
+          & $env:CODEQL_BIN pack download codeql/cpp-queries@0.9.0
+
+      - name: Creating CodeQL Database & Build Drivers
+        shell: pwsh
+        run: |
+          Write-Host "[+] Creating CodeQL Database..."
+
+          # Use & (call operator) with $env: variables
+          & $env:CODEQL_BIN database create "$env:X64_DB_PATH" `
+              --language=cpp `
+              --command "pwsh -NoProfile -ExecutionPolicy Bypass -File `"$env:WDS_PATH\Build-AllSamples.ps1`" -Configuration Release -Platform x64 -Verbose"
+
+          if ($LASTEXITCODE -ne 0) {
+              Write-Error "[!] Database creation failed with error $LASTEXITCODE"
+              exit $LASTEXITCODE
+          }
 
       - name: Setup Pre-Requisites
         run: echo Hello, world!
